server:
  port: 8082
spring:
  application:
    name: oauth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: Aba14mah?
#  security:
#    oauth2:
#      authorization-server:
#        client:
#          client-id: client
#          client-secret: secret
#          scope: read,write
#          authorization-grant-types: authorization_code,refresh_token,client_credentials
#          redirect-uri: http://localhost:8080/login/oauth2/code/client
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
  main:
  allow-bean-definition-overriding: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG

